#!/usr/bin/env php
<?php

exit(call_user_func(function () {
    define('ARTEFAKT_START', microtime(true));

    // Require the autoloader
    require __DIR__.DIRECTORY_SEPARATOR.'vendor'.DIRECTORY_SEPARATOR.'autoload.php';

    $artefakt = new \Artefakt\Artefakt\Ports\ArtefaktCommand(
        glob(__DIR__.DIRECTORY_SEPARATOR.'vendor'.DIRECTORY_SEPARATOR.'*'.DIRECTORY_SEPARATOR.'*'.DIRECTORY_SEPARATOR.'composer.json')
    );

    return $artefakt->run();
}));

